image: Visual Studio 2015
platform:
  - x86
  - x64

environment:
  matrix:
    - nodejs_version: 8
    - nodejs_version: 10
    - nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version
  - npm i

test_script:
  - npm test