image: Visual Studio 2015
platform:
  - x64
  - x86

environment:
  matrix:
    - nodejs_version: 8.9
    - nodejs_version: 10
    - nodejs_version: 12

install:
  - ps: Install-Product node $env:nodejs_version  $env:platform
  - npm i

test_script:
  - npm test